// <auto-generated />
using System;
using Infrastructure.DataConfiguration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(InfrastructureDbContext))]
    [Migration("20241120234043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.AccountPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("AccountPayment");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.CreditPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("CreditPayment");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.Driver17To25", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Exists17To25")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Driver17To25s");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.DriverP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Driver17To25Id")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LivesWithInsured")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipToInsured")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Driver17To25Id");

                    b.ToTable("DriverPs");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.Insured", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneAreaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipToOwner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Insured");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.OpportuniteLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsuredId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("InsuredId");

                    b.ToTable("OpportuniteLeads");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.PaymentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountPaymentId")
                        .HasColumnType("int");

                    b.Property<int?>("CreditPaymentId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountPaymentId");

                    b.HasIndex("CreditPaymentId");

                    b.ToTable("PaymentData");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.SolicitationLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GuidSolicitation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("OpportuniteLeadId")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("PrimaryDriverId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TransmissionId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("OpportuniteLeadId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PrimaryDriverId");

                    b.HasIndex("TransmissionId");

                    b.HasIndex("VehicleId");

                    b.ToTable("SolicitationLeads");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.Transmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinalValidityDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InitialValidityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Insurer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsurerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transmissions");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CirculationZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsNew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OvernightLocation")
                        .HasColumnType("int");

                    b.Property<string>("OvernightZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResidentialGarage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResidentialZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsageProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("WorkGarage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsageProfileId");

                    b.HasIndex("VehicleDetailsId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.VehicleDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleDetails");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.VehicleUsageProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Usage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VehicleUsageProfiles");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.DriverP", b =>
                {
                    b.HasOne("Infrastructure.Repository.Leads.Commands.Driver17To25", "Driver17To25")
                        .WithMany()
                        .HasForeignKey("Driver17To25Id");

                    b.Navigation("Driver17To25");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.OpportuniteLead", b =>
                {
                    b.HasOne("Infrastructure.Repository.Leads.Commands.Insured", "Insured")
                        .WithMany()
                        .HasForeignKey("InsuredId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insured");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.PaymentData", b =>
                {
                    b.HasOne("Infrastructure.Repository.Leads.Commands.AccountPayment", "AccountPayment")
                        .WithMany()
                        .HasForeignKey("AccountPaymentId");

                    b.HasOne("Infrastructure.Repository.Leads.Commands.CreditPayment", "CreditPayment")
                        .WithMany()
                        .HasForeignKey("CreditPaymentId");

                    b.Navigation("AccountPayment");

                    b.Navigation("CreditPayment");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.SolicitationLead", b =>
                {
                    b.HasOne("Infrastructure.Repository.Leads.Commands.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("Infrastructure.Repository.Leads.Commands.OpportuniteLead", "OpportuniteLead")
                        .WithMany()
                        .HasForeignKey("OpportuniteLeadId");

                    b.HasOne("Infrastructure.Repository.Leads.Commands.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("Infrastructure.Repository.Leads.Commands.DriverP", "PrimaryDriver")
                        .WithMany()
                        .HasForeignKey("PrimaryDriverId");

                    b.HasOne("Infrastructure.Repository.Leads.Commands.Transmission", "Transmission")
                        .WithMany()
                        .HasForeignKey("TransmissionId");

                    b.HasOne("Infrastructure.Repository.Leads.Commands.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.Navigation("Comment");

                    b.Navigation("OpportuniteLead");

                    b.Navigation("Owner");

                    b.Navigation("PrimaryDriver");

                    b.Navigation("Transmission");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Infrastructure.Repository.Leads.Commands.Vehicle", b =>
                {
                    b.HasOne("Infrastructure.Repository.Leads.Commands.VehicleUsageProfile", "UsageProfile")
                        .WithMany()
                        .HasForeignKey("UsageProfileId");

                    b.HasOne("Infrastructure.Repository.Leads.Commands.VehicleDetails", "VehicleDetails")
                        .WithMany()
                        .HasForeignKey("VehicleDetailsId");

                    b.Navigation("UsageProfile");

                    b.Navigation("VehicleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
